#ifndef __IpGame__DictConWayEnum__
#define __IpGame__DictConWayEnum__

enum DictConWayEnum {
	
	DictConWayEnumTaskCommonReward=1,//普通任务奖励
	DictConWayEnumTaskDailyReward=2,//日常任务奖励
	DictConWayEnumTaskDailyRefresh=3,//日常任务刷新
	DictConWayEnumTaskDailyProgressReward=4,//日常任务进度奖励
	DictConWayEnumTaskWantedReward=5,//悬赏任务奖励
	DictConWayEnumTaskWantedRefresh=6,//悬赏任务刷新
	DictConWayEnumTaskWantedProgressReward=7,//日常任务进度奖励
	DictConWayEnumHeroLevelUp=8,//武将等级提升
	DictConWayEnumHeroQualityUp=9,//武将品质提升
	DictConWayEnumHeroPrestigeUp=10,//武将声望提升
	DictConWayEnumHeroBookCompose=11,//武将书信合成
	DictConWayEnumEquipHarden=12,//装备强化
	DictConWayEnumEquipForge=13,//装备熔炼
	DictConWayEnumEquipCompose=14,//装备材料合成
	DictConWayEnumItemSell=15,//道具出售
	DictConWayEnumItemUse=16,//道具使用
	DictConWayEnumTownRecruit1Reward=17,//普通招募奖励
	DictConWayEnumTownRecruit2Reward=18,//高级招募奖励
	DictConWayEnumTownRecruit3Reward=19,//超级招募奖励
	DictConWayEnumTownFindingReward=20,//寻访奖励
	DictConWayEnumTownShoppingBuy=21,//商店购买
	DictConWayEnumMarketBuy=22,//拍卖行购买
	DictConWayEnumMarketSoldOut=23,//拍卖行下架
	DictConWayEnumMarketSell=24,//拍卖出售
	DictConWayEnumStageBattleReward=25,//名战役战斗奖励
	DictConWayEnumStageBattleLootReward=26,//名战役战斗翻牌奖励
	DictConWayEnumStageBattleSweepReward=27,//关卡战斗扫荡奖励
	DictConWayEnumStageBattleStarReward=28,//名战役星级奖励
	DictConWayEnumStageBiograghyReward=29,//名将传战斗奖励
	DictConWayEnumStageBiograghyLootReward=30,//名将传战斗翻牌奖励
	DictConWayEnumStageBiograghyStarReward=31,//名将传星级奖励
	DictConWayEnumStageInfiniteReward=32,//三国无双战斗奖励
	DictConWayEnumStageInfiniteLootReward=33,//三国无双战斗翻牌奖励
	DictConWayEnumWarScoutReward=34,//霸业侦察战斗奖励
	DictConWayEnumWarScoutStarReward=35,//霸业侦察星级奖励
	DictConWayEnumWarThroneReward=36,//霸业争夺战斗奖励
	DictConWayEnumWarThroneRankingReward=37,//霸业争夺排名奖励
	DictConWayEnumWarSiegeReward=38,//霸业讨伐战斗奖励
	DictConWayEnumWarSiegeRankingReward=39,//霸业讨伐排名奖励
	DictConWayEnumWarVictoryReward=40,//霸业讨伐获胜奖励
	DictConWayEnumWarShoppingBuy=41,//荣誉商店购买
	DictConWayEnumWarShoppingSell=42,//荣誉商店出售
	DictConWayEnumSettingNameReward=43,//主角名称设定奖励
	DictConWayEnumVipDailyReward=44,//VIP日常领取
	DictConWayEnumVipLevelUpReward=45,//VIP升级奖励
	DictConWayEnumVipShoppingBuy=46,//黑市购买
	DictConWayEnumVipShoppingRefresh=47,//黑市刷新
	DictConWayEnumChat=48,//聊天
	DictConWayEnumMailReward=49,//邮件获得
	DictConWayEnumMoneyChange=50,//强征
	DictConWayEnumGoldCharge=51,//元宝充值
	DictConWayEnumPowerChange=52,//购买体力
	DictConWayEnumPowerAddQuartz=53,//定点体力增加
	DictConWayEnumActivitySignReward=54,//签到活动奖励
	DictConWayEnumActivityTurntableReward=55,//转盘活动奖励
	DictConWayEnumActivityPlayerLevelReward=56,//冲级达人活动奖励
	DictConWayEnumActivityRechargeReturnReward=57,//充值返现活动奖励
	DictConWayEnumActivityFirstChargeReward=58,//首充活动奖励
	DictConWayEnumActivityOpenServerReward=59,//开服活动奖励
	DictConWayEnumActivitySendGiftReward=60,//礼包活动奖励
	DictConWayEnumActivitySevenTaskReward=61,//7日活动任务奖励 
	DictConWayEnumActivitySevenTaskStarReward=62,//7日活动星级奖励
	DictConWayEnumCreatePlayer=63,//创建角色
	DictConWayEnumActivateCode=64,//激活码
	DictConWayEnumGM=65//GM
};
#endif