#ifndef __IpGame__DictFunctionEnum__
#define __IpGame__DictFunctionEnum__

enum DictFunctionEnum {
	
	DictFunctionEnumNormalSkill=1,//普通技能
	DictFunctionEnumCoolDownSkill=2,//必杀技能1
	DictFunctionEnumCostRageSkill=3,//怒气技能
	DictFunctionEnumTaskCommon=4,//普通任务
	DictFunctionEnumTaskDaily=5,//日常任务
	DictFunctionEnumTaskWanted=6,//悬赏任务
	DictFunctionEnumLineup=7,//阵容
	DictFunctionEnumHero=8,//所属武将
	DictFunctionEnumBook=9,//所属书信
	DictFunctionEnumEquip=10,//所属装备
	DictFunctionEnumMater=11,//所属材料
	DictFunctionEnumItem=12,//所属道具
	DictFunctionEnumHeroQuality=13,//武将觉醒
	DictFunctionEnumHeroProp=14,//武将详情
	DictFunctionEnumHeroSkill=15,//武将技能
	DictFunctionEnumHeroPrestige=16,//武将历练
	DictFunctionEnumEquipHarden=17,//装备强化
	DictFunctionEnumEquipForge=18,//装备熔炼
	DictFunctionEnumLead=19,//招募
	DictFunctionEnumFind=20,//寻访
	DictFunctionEnumShopping=21,//商店
	DictFunctionEnumMarket=22,//拍卖
	DictFunctionEnumCampaign=23,//名战役
	DictFunctionEnumLegend=24,//名将传
	DictFunctionEnumMusou=25,//三国无双
	DictFunctionEnumClearing=26,//扫荡
	DictFunctionEnumCampaignElite=27,//名战役精英
	DictFunctionEnumScout=28,//霸业侦查
	DictFunctionEnumCrusade=29,//霸业讨伐
	DictFunctionEnumThrone=30,//霸业驻守
	DictFunctionEnumShoppingGlory=31,//荣誉商店
	DictFunctionEnumArena=32,//竞技场
	DictFunctionEnumStory=33,//剧情
	DictFunctionEnumNewGuide=34,//新手指引
	DictFunctionEnumFunction=35,//功能开启
	DictFunctionEnumActivity=36,//活动
	DictFunctionEnumSetting=37,//设置
	DictFunctionEnumChat=38,//聊天
	DictFunctionEnumMail=39,//邮件
	DictFunctionEnumGemstoneMine=40,//矿车
	DictFunctionEnumGoldCharge=41,//元宝充值
	DictFunctionEnumPowerCharge=42,//购买体力
	DictFunctionEnumFigntCapaBatter=43,//如何变强
	DictFunctionEnumBlackShop=44,//黑市
	DictFunctionEnumVip=45,//VIP
	DictFunctionEnumSign=46,//签到
	DictFunctionEnumLucky=47,//祈福
	DictFunctionEnumSevenDay=48,//七日活动
	DictFunctionEnumCampaignStage=49,//名战役关卡
	DictFunctionEnumCampaignEliteChapter=50,//名战役精英章节
	DictFunctionEnumCampaignEliteStage=51,//名战役精英关卡
	DictFunctionEnumCoolDownSkill2=52,//必杀技能2
	DictFunctionEnumCoolDownSkill3=53,//必杀技能3
	DictFunctionEnumDodgeParrySkill=54,//闪避格挡技能
	DictFunctionEnumTheMainCity=55,//主城
	DictFunctionEnumHelpPosition=56,//助阵位
	DictFunctionEnumEatBlood=57,//血瓶功能
	DictFunctionEnumChestFunction=58,//宝箱功能
	DictFunctionEnumGift=59,//礼包
	DictFunctionEnumCampaignChapter=60,//名战役章节
	DictFunctionEnumWelfareDay=61,//每日福利
	DictFunctionEnumHeroStar=62,//武将升星
	DictFunctionEnumBanquet=63,//宴席
	DictFunctionEnumWelfareWeek=64,//每周福利
	DictFunctionEnumScroll=65,//卷轴
	DictFunctionEnumHeroEquip=66,//武将装备
	DictFunctionEnumFirstCharge=67//首充
};
#endif