//
//  UserCustomEvent.h
//  FightPass
//
//  Created by zhangxiaobin on 15/6/12.
//
//

#ifndef __FightPass__UserCustomEvent__
#define __FightPass__UserCustomEvent__
#include "cocos2d.h"
USING_NS_CC;
using namespace std;

static char CUSTOM_SDK_LOGINSUC[] = "CUSTOM_SDK_LOGINSUC";//登录成功
static char CUSTOM_SDK_LOGINCANCEL[] = "CUSTOM_SDK_LOGINCANCEL";//登录取消
static char CUSTOM_CONFIG_UPDATE_SUC[] = "CUSTOM_CONFIG_UPDATE_SUC";//配置文件更新
static char CUSTOM_RESOURCE_UPDATE_SUC[] = "CUSTOM_RESOURCE_UPDATE_SUC";//资源更新成功
static char CUSTOM_CLIENTAPP_SUC[] = "CUSTOM_CLIENTAPP_SUC";//客户端更新成功
static char CUSTOM_UPDATE_USERPROP_VALUE[] = "CUSTOM_UPDATE_USERPROP_VALUE";//更新玩家基本属性
static char CUSTOM_UPDATE_USER_LEVEL[] = "CUSTOM_UPDATE_USER_LEVEL";//玩家升级
static char CUSTOM_UPDATE_USER_RAIDSCARD[] = "CUSTOM_UPDATE_USER_RAIDSCARD";//更新扫荡令
static char CUSTOM_UPDATE_USER_ITEMS[] = "CUSTOM_UPDATE_USER_ITEMS";//更新玩家道具
static char CUSTOM_SHOW_SIMPLEPAD[] = "CUSTOM_SHOW_SIMPLEPAD";//显示摇杆
static char CUSTOM_ON_SKILL_ATTACK[] = "CUSTOM_ON_SKILL_ATTACK";  //技能第一次攻击
static char CUSTOM_SHOW_FULLSCREEN[] = "CUSTOM_SHOW_FULLSCREEN";//显示全屏特效
static char CUSTOM_CAMERA_IN[] = "CUSTOM_CAMERA_IN";//拉近摄像机
static char CUSTOM_CAMERA_RESET[] = "CUSTOM_CAMERA_RESET";//重置摄像机
static char CUSTOM_SORT_BORN_MONSTER[] = "CUSTOM_SORT_BORN_MONSTER";//排序怪

static char CUSTOM_SKILL1_CD[] = "CUSTOM_SKILL1_CD";//技能cd
static char CUSTOM_SKILL2_CD[] = "CUSTOM_SKILL2_CD";//技能2
static char CUSTOM_SKILL3_CD[] = "CUSTOM_SKILL3_CD";//技能3
static char CUSTOM_SKILL4_CD[] = "CUSTOM_SKILL4_CD";//超大招cd
static char CUSTOM_SKILL5_CD[] = "CUSTOM_SKILL5_CD";//闪避格档cd
static char CUSTOM_SHOW_HEALTHWARNING[] = "CUSTOM_SHOW_HEALTHWARNING";//显示生命警示
static char CUSTOM_HIDE_HEALTHWARNING[] = "CUSTOM_HIDE_HEALTHWARNING";//隐藏生命警示

static char CUSTOM_SHOW_SKILL1_BTN[] = "CUSTOM_SHOW_SKILL1_BTN";//显示技能按钮
static char CUSTOM_SHOW_SKILL3_BTN[] = "CUSTOM_SHOW_SKILL3_BTN";
static char CUSTOM_SHOW_SKILL2_BTN[] = "CUSTOM_SHOW_SKILL2_BTN";
static char CUSTOM_SHOW_PROTECTED_BTN[] = "CUSTOM_SHOW_PROTECTED_BTN";

static char CUSTOM_SKILL4_OVER[] = "CUSTOM_SKILL4_OVER";//大招结束
static char CUSTOM_PLAY_SOUND[] = "CUSTOM_PLAY_SOUND";
static char CUSTOM_BATTLE_FLASHMOVE[] = "CUSTOM_BATTLE_FLASHMOVE";//闪退 或闪击
static char CUSTOM_CAMERA_MOVESELF[] = "CUSTOM_CAMERA_MOVESELF";//摄像机移动到自己
static char CUSTOM_CAMERA_MOVEENEMY[] = "CUSTOM_CAMERA_MOVEENEMY";//摄像机移动到敌方
static char CUSTOM_CAMERA_MOVEUP[] = "CUSTOM_CAMERA_MOVEUP";//摄像机上移
static char CUSTOM_CAMERA_MOVEDOWN[] = "CUSTOM_CAMERA_MOVEDOWN";//摄像机下移
static char CUSTOM_CAMERA_SCALE[]  = "CUSTOM_CAMERA_SCALE";//缩放镜头事件
static char CUSTOM_HIDE_MAPRESOURCE[] = "CUSTOM_HIDE_MAPRESOURCE";
static char CUSTOM_SHOW_MAPREOURCE[] = "CUSTOM_SHOW_MAPREOURCE";//大招结束显示场景资源
static char CUSTOM_PAUSE_AVATAR_ACTION[] = "CUSTOM_PAUSE_AVATAR_ACTION";//暂停所有人的动作
static char CUSTOM_RESET_AVATAR_ACTION[] = "CUSTOM_RESET_AVATAR_ACTION";//恢复所有人的动作
static char CUSTOM_BATTLE_RELEASEBIGSKILL[] = "CUSTOM_BATTLE_RELEASEBIGSKILL";//释放大招
static char CUSTOM_BATTLE_CHANGESKILLBG[] = "CUSTOM_BATTLE_CHANGESKILLBG";//更换技能背景资源
static char CUSTOM_BATTLE_HIDEOTHER[] = "CUSTOM_BATTLE_HIDEOTHER";//
static char CUSTOM_BATTLE_SHOWOTHER[] = "CUSTOM_BATTLE_SHOWOTHER";//
static char CUSTOM_BATTLE_SHAKE[] = "CUSTOM_BATTLE_SHAKE";//震屏
static char CUSTOM_POSITION_MOVE[] = "CUSTOM_POSITION_MOVE";//位移
static char CUSTOMM_STOP_ACTION[] = "CUSTOMM_STOP_ACTION";//定身
static char CUSTOM_ACTION_LOOP[] = "CUSTOM_ACTION_LOOP";
static char CUSTOM_BATTLE_QUITBATTLE[] = "CUSTOM_BATTLE_QUITBATTLE";//退出战场
static char CUSTOM_BATTLE_REPLAY[] = "CUSTOM_BATTLE_REPLAY";//重来一次
static char CUSTOM_BATTLE_CHANGE_MAINHERO[] = "CUSTOM_BATTLE_CHANGE_MAINHERO";//更换主将
static char CUSTOM_BATTLE_EAT_BLOODBOTTLE[] = "CUSTOM_BATTLE_EAT_BLOODBOTTLE";//吃血瓶
static char CUSTOM_BATTLE_MONSTER_DEAD[] = "CUSTOM_BATTLE_MONSTER_DEAD";//怪物死亡
static char CUSTOM_BATTLE_HERO_DEAD[] = "CUSTOM_BATTLE_HERO_DEAD";//英雄死亡
static char CUSTOM_BATTLE_HERO_LIFETIME[] = "CUSTOM_BATTLE_HERO_LIFETIME";//援助时间到
static char CUSTOM_BATTLE_SUMMONED_SKILL[] = "CUSTOM_BATTLE_SUMMONED_SKILL";//召唤技能

static char CUSTOM_BATTLE_HERO_REBORNCONFIRM[] = "CUSTOM_BATTLE_HERO_REBORNCONFIRM";//英雄重生确定
static char CUSTOM_BATTLE_HERO_REBORNCANCEL[] = "CUSTOM_BATTLE_HERO_REBORNCANCEL";//英雄重生取消
static char CUSTOM_BATTLE_SHOW_BOSS_WARNING[] = "CUSTOM_BATTLE_SHOW_BOSS_WARNING";//强敌来袭

static char CUSTOM_MARKER_HEROLAYER[] = "CUSTOM_MARKER_HEROLAYER";//跳转获得英雄层
static char CUSTOM_MARKER_EQUIPLAYER[] = "CUSTOM_MARKER_EQUIPLAYER";//跳转获得物品层
static char CUSTOM_MARKER_CTEATTENITEM[] = "CUSTOM_MARKER_CTEATTENITEM";//跳转十连抽物品层
static char CUSTOM_MARKER_XIAJIABTN[] = "CUSTOM_MARKER_XIAJIABTN";// 下架
static char CUSTOM_MARKER_FINDTIPS[] = "CUSTOM_MARKER_FINDTIPS";// 显示tips

static char CUSTOM_MARKER_HEROLOADED[] = "CUSTOM_MARKER_HEROLOADED";//资源加载完成
static char CUSTOM_MARKER_KAISHIXUNFANG[] = "CUSTOM_MARKER_KAISHIXUNFANG";//开始寻访
static char CUSTOM_MARKER_SUREJAISU[] = "CUSTOM_MARKER_SUREJAISU";// 确认加速
static char CUSTOM_MARKER_LINGDIKUOZHAN[] = "CUSTOM_MARKER_LINGDIKUOZHAN";// 扩展成功

static char CUSTOM_MARKER_UPDATASHOP[] = "CUSTOM_MARKER_UPDATASHOP";// 跟新商店层
static char CUSTOM_MARKER_FINDERSTART[] = "CUSTOM_MARKER_FINDERSTART";// 加入寻访者
static char CUSTOM_MARKER_SUCCEEDBUY[] = "CUSTOM_MARKER_SUCCEEDBUY";// 购买成功
static char CUSTOM_MARKER_CHANGECARDPOS[] = "CUSTOM_MARKER_CHANGECARDPOS";// 举贤 改变卡牌位置


static char CUSTOM_CHANGE_TEAMPAGE[] = "CUSTOM_CHANGE_TEAMPAGE";//更换阵容
static char CUSTOM_LINEUP_SAHNGZHENWUJIANG[] = "CUSTOM_LINEUP_SAHNGZHENWUJIANG";//上阵武将
static char CUSTOM_LINEUP_ZHUZHENWUJIANG[] = "CUSTOM_LINEUP_ZHUZHENWUJIANG";//助阵武将
static char CUSTOM_LINEUP_QIEHUANWUJIANG[] = "CUSTOM_LINEUP_QIEHUANWUJIANG";//切换武将
static char CUSTOM_LINEUP_ENTERHEROLIST[] = "CUSTOM_LINEUP_ENTERHEROLIST";//切换武将
static char CUSTOM_LINEUP_LEADERSHIP[] = "CUSTOM_LINEUP_LEADERSHIP";//领导力
static char CUSTOM_LINEUP_ZHANLI[] = "CUSTOM_LINEUP_ZHANLI";//战力
static char CUSTOM_LINEUP_ROLELEADERSHIP[] = "CUSTOM_LINEUP_ROLELEADERSHIP";//角色领导力
static char CUSTOM_LINEUP_FIGHTORWITE[] = "CUSTOM_LINEUP_FIGHTORWITE";//开战还是待战
static char CUSTOM_LINEUP_FIRSTCREATELINEUP[] = "CUSTOM_LINEUP_FIRSTCREATELINEUP";//第一次创建阵容

static char CUSTOM_ENTER_BATTLE[] = "CUSTOM_ENTER_BATTLE";//进入战斗
static char CUSTOM_BEFOREFIGHT_TALK_END[] = "CUSTOM_START_TALK_END";// 开始剧情结束
static char CUSTOM_OVERFIGHT_TALK_END[] = "CUSTOM_OVERFIGHT_TALK_END";//over剧情结束
static char CUSTOM_MONSTER_TALK_END[] = "CUSTOM_MONSTER_TALK_END";//怪物说话完毕
static char CUSTOM_BATTLE_COUNTDOWN_OVER[] = "CUSTOM_BATTLE_COUNTDOWN_OVER";//倒计时结束

static char CUSTOM_HIDE_SCENE_FUN[] = "CUSTOM_HIDE_SCENE_FUN";//隐藏场景里一些功能
static char CUSTOM_SHOW_SCENE_FUN[] = "CUSTOM_SHOW_SCENE_FUN";//显示场景里一些功能
static char CUSTOM_RESET_CHAPTER_TYPE[] = "CUSTOM_RESET_CHAPTER_TYPE";//重置关卡类型

static char CUSTOM_CHOOSE_CARD_OVER_FUN[]="CUSTOM_CHOOSE_CARD_OVER_FUN";//添加装备完成

static char CUSTOM_ADD_CARD_FUN[]="CUSTOM_ADD_CARD_FUN";//加武将
static char CUSTOM_ADD_EQIUP_FUN[]="CUSTOM_ADD_EQIUP_FUN";//添加装备
static char CUSTOM_REMOVE_CARD_FUN[]="CUSTOM_REMOVE_CARD_FUN";//删除武将
static char CUSTOM_START_FUN[]="CUSTOM_START_FUN";//刷新卡牌
static char CUSTOM_UPDATE_EQUIP[] = "CUSTOM_UPDATE_EQUIP";//刷新装备
static char CUSTOM_AWAKE_FUN[]="CUSTOM_AWAKE_FUN";//觉醒特效
static char CUSTOM_CHOOSE_HERO_FUN[]="CUSTOM_CHOOSE_HERO_FUN";//选择列表中的武将
static char CUSTOM_EFFECTEND_EVENT[]="CUSTOM_EFFECTEND_EVENT";//特效结束
static char CUSTOM_HEROPUTONEQUIP[]="CUSTOM_HEROPUTONEQUIP";//武将穿上或脱下装备；

static char CUSTOM_SIGNIN_SENDMESSAGE_EVENT[]="CUSTOM_SIGNIN_SENDMESSAGE_EVENT";//签到模块发送消息
static char CUSTOM_UPDATE_NICK_NAME[] = "CUSTOM_UPDATE_NICK_NAME";//更新昵称
static char CUSTOM_UPDATE_VIP_LEVEL[] = "CUSTOM_UPDATE_VIP_LEVEL";//更新vip等级
static char CUSTOM_UPDATE_VERSION[] = "CUSTOM_UPDATE_VERSION";//更新版本号
static char CUSTOM_VIP_BLACKSHOP_SHHUAXIN[]="CUSTOM_VIP_BLACKSHOP_SHHUAXIN";//黑市刷新
static char CUSTOM_VIP_BLACKSHOP_BUY[]="CUSTOM_VIP_BLACKSHOP_BUY";//黑市购买
static char CUSTOM_VIP_LIBAO_BUY[]="CUSTOM_VIP_LIBAO_BUY";//LIBAO购买

static char CUSTOM_JUXIAN_TOUCHTURN[]="CUSTOM_JUXIAN_TOUCHTURN";//举贤点击跳转
static char CUSTOM_MAIL_MAILCELLINGQUSUEEM[]="CUSTOM_MAIL_MAILCELLINGQUSUEEM";//邮件领取成功

static char CUSTOM_CHAT_MESSAGE_CLICK[]="CUSTOM_CHAT_MESSAGE_CILCK";//点击消息列表内容；
static char CUSTOM_CHAT_FRIEND_CLICK[]="CUSTOM_CHAT_FRIEND_CLICK";//点击好友列表内容；

static char CUSTOM_WEEK_CHOSE_HERO[]="CUSTOM_WEEK_CHOSE_HERO";//选择领取哪个英雄；

static char CUSTOM_SELL_HERO[]="CUSTOM_SELL_HERO";//出售武将了
static char CUSTOM_SELL_EQUIP[]="CUSTOM_SELL_EQUIP";//出售装备了

static char CUSTOM_MARKET_SETCH[]="CUSTOM_MARKET_SETCH";//拍卖所搜索
//refresh
static char CUSTOM_REFRESH_DOT[]="CUSTOM_REFRESH_DOT";//刷新红点

static char CUSTOM_ARENA_FIGHT_INDEX[] = "CUSTOM_ARENA_FIGHT_INDEX";//竞技场战斗选择
static char CUSTOM_ARENA_FIGHT_SUCCEED[] = "CUSTOM_ARENA_FIGHT_SUCCEED";//竞技场战斗购买成功
static char CUSTOM_UPDATE_HEROBASEPAGEMSG[] = "CUSTOM_UPDATE_HEROBASEPAGEMSG";//更新武将基础信息

//------------------------------------------------好友部分------------------------------------------------------------------------//
static char CUSTOM_DELETE_FRIEND[]="CUSTOM_DELETE_FRIEND";//删除好友
static char CUSTOM_REFRESH_APPLY[]="CUSTOM_REFRESH_APPLY";//刷新申请列表refresh
static char CUSTOM_ALTER_HEAD[]="CUSTOM_ALTER_HEAD";//修改头像成功
static char CUSTOM_YAYA_CHANNELLOGIN_SUC[] = "CUSTOM_YAYA_CHANNELLOGIN_SUC";//yaya频道登陆成功

static char CUSTOM_SEVENDAY_REDPOINT[] = "CUSTOM_SEVENDAY_REDPOINT";//七日红点
static char CUSTOM_SEVENDAY_MODULE_REDPOINT[] = "CUSTOM_SEVENDAY_MODULE_REDPOINT";//七日模块红点



#endif /* defined(__FightPass__UserCustomEvent__) */
